### ISSUE TITLE
Convar maxclients

### ISSUE THREAD

**Issue by ByteServer** [NFive/plugin-sessionmanager#1]
SessionManager gives me an error when OnRequest is happening is it a fault from my end?
i can fix it by replacing this.Configuration.MaxClients with (ushort)32

Thanks

**Comment by Igirisujin** [comment]
Could you post the full error? I don't get any errors myself

**Comment by Igirisujin** [comment]
Do you have a plugin-sessionmanager.yml file inside of your nfive config folder? Recent changes to session manager have made it a configurable controller and I'm guessing that nfive isn't playing nicely when a config isn't available.

**Comment by ByteServer** [comment]
Yeah i have the yml file in the config folder, but its empty just like the plugin-queue.yml i realised that when it started complaining about configuration files haha 😄.. Well maybe it will fix itself in a future update 😀

**Comment by JoeBiellik** [comment]
I was just able to recreate this issue with the following:
```
nfpm setup
nfpm install NFive/plugin-sessionmanager
nfpm install NFive/plugin-queue
nfpm start
```

You get an missing file error as ``config/plugin-sessionmanager.yml`` and ``config/plugin-queue.yml`` don't exist, creating empty files gives @ByteServer's error.

Adding the following solves the issue:

plugin-sessionmanager.yml:
```
connection_timeout: 60000
reconnect_grace: 120000
```

plugin-queue.yml:
```
disconnect_grace: 60000
connection_timeout: 60000
deferral_delay: 500
max_clients: 5
queue_when_not_full: false
server_name: "test"
```

This issue is down to how nfpm handles config management, and should be fixed soon at package manager level.

**Comment by ByteServer** [comment]
Well damn, Joe saves the day, thanks mate! 😄 👍 So it was just a config file issue.
But anyways many thanks, and i am a very big fan of your projects, so keep up the good work guys, cant wait to see more from you two 👀
